export const data = [
  {
    id: 1,
    PossessionHome: 40,
    PossessionAway: 60,
    TotalAttacksHome: 24,
    TotalAttacksAway: 9,
    ShotHome: 13,
    ShoTotalAttackAwayay: 10,
    ShotOnGoalHome: 4,
    ShotOnGoalAway: 2,
    CornerHome: 1,
    CornerAway: 0,
    OffsideHome: 0,
    OffsideAway: 0,
    YellowcardHome: 1,
    YellowCardAway: 0,
    RedCardHome: 0,
    RedcardAway: 0,
  },
  {
    id: 2,
    PossessionHome: 43,
    PossessionAway: 57,
    TotalAttacksHome: 30,
    TotalAttackAway: 10,
    ShotHome: 13,
    Shot: 7,
    SOGH: 5,
    SOGW: 2,
    CH: 1,
    CW: 0,
    OFFH: 0,
    OFFA: 0,
    YCH: 1,
    YCA: 0,
    RCH: 0,
    RCA: 1,
  },
  {
    id: 3,
    PossessionHome: 20,
    PossessionAway: 80,
    TotalAttacksHome: 35,
    TotalAttackAway: 11,
    ShotHome: 13,
    Shot: 7,
    SOGH: 4,
    SOGW: 2,
    CH: 1,
    CW: 0,
    OFFH: 0,
    OFFA: 0,
    YCH: 1,
    YCA: 0,
    RCH: 0,
    RCA: 0,
  },
  {
    id: 4,
    PossessionHome: 50,
    PossessionAway: 50,
    TotalAttacksHome: 35,
    TotalAttackAway: 20,
    ShotHome: 13,
    Shot: 7,
    SOGH: 4,
    SOGW: 2,
    CH: 1,
    CW: 0,
    OFFH: 0,
    OFFA: 0,
    YCH: 1,
    YCA: 0,
    RCH: 0,
    RCA: 1,
  },
];

export const button = ["Details", "Stats", "Lineups", "H2H"];
